add kruise-rollout addons
kubevela/catalog pull request #328
Opened 2022-04-22 08:27 UTC by zmberg

Signed-off-by: liheng.zms <liheng.zms@alibaba-inc.com>

### Description of your changes
add kruise-rollout addons

2022-04-22 08:28 UTC, msftgits commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/oam-dev/catalog?pullRequest=328) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/catalog?pullRequest=328) before we can accept your contribution.<br/><br/>:x: zmberg [sign now](https://cla.opensource.microsoft.com/oam-dev/catalog?pullRequest=328)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/catalog?pullRequest=328) it.</sub>

2022-04-25 02:10 UTC, barnettZQG commented on experimental/addons/kruise-rollout/template.yaml
> +        chart: kruise-rollout
The controller deployed 2 instances default?

2022-04-25 02:14 UTC, barnettZQG commented on experimental/addons/kruise-rollout/definitions/kruise-rollout.cue
> +		auto: *false | bool
Please add the help message for the field.
```
// +usage=xxxx
```

2022-04-25 02:16 UTC, barnettZQG commented on experimental/addons/kruise-rollout/definitions/kruise-rollout.cue
> +		service:            *"" | string
```suggestion
		service?:             string
```

2022-04-25 02:16 UTC, barnettZQG commented on experimental/addons/kruise-rollout/definitions/kruise-rollout.cue
> +		ingress: name: *"" | string
```suggestion
		ingress: name?: string
```

2022-04-25 02:46 UTC, wangyikewxgm commented
Cause the experimental addon won't be tested by default, please add test like [argocd](https://github.com/oam-dev/catalog/blob/38ed00362197ad6256dd710653922accb614446a/test/e2e-test/hack/addon-vela-test.sh#L31).

2022-04-25 03:49 UTC, wonderflow commented
> Cause the experimental addon won't be tested by default, please add test like [argocd](https://github.com/oam-dev/catalog/blob/38ed00362197ad6256dd710653922accb614446a/test/e2e-test/hack/addon-vela-test.sh#L31).

This should be an official addon instead of experimental, right?

2022-05-11 07:19 UTC, Somefive commented
```cue
"kruise-rollout": {
	type: "trait"
	annotations: {}
	labels: {}
	description: "Rollout workload by kruise controller."
	attributes: {
		podDisruptive: true
		appliesToWorkloads: ["*"]
		status: {
			customStatus: #"""
				message: context.outputs.rollout.status.message
				"""#
			healthPolicy: #"""
				isHealth: context.outputs.rollout.status.phase == "Healthy"
				"""#
		}
	}
}
template: {
	#CanaryStep: {
		weight?:   int
		replicas?: int | string
		duration?: int
	}
	#TrafficRouting: {
		// use context.name as service if not filled
		service:            *"" | string
		gracePeriodSeconds: *5 | int
		type:               "nginx" | "alb"
		ingress: name: *"" | string
	}
	parameter: {
		auto: *false | bool
		canary: {
			steps: [...#CanaryStep]
			trafficRoutings?: [...#TrafficRouting]
		}
	}

    srcName: context.output.metadata.name

	outputs: rollout: {
		apiVersion: "rollouts.kruise.io/v1alpha1"
		kind:       "Rollout"
		metadata: {
			name:      context.name
			namespace: context.namespace
		}
		spec: {
			objectRef: {
				workloadRef: {
					apiVersion: context.output.apiVersion
					kind:       context.output.kind
                    if srcName != _|_ {
                        name: srcName
                    }
                    if srcName == _|_ {
                        name: context.name
                    }
				}
			}
			strategy: {
				canary: {
					steps: [
						for k, v in parameter.canary.steps {
							if v.weight != _|_ {
								weight: v.weight
							}

							if v.canaryReplicas != _|_ {
								replicas: v.replicas
							}

							pause: {
								if parameter.auto {
									duration: 0
								}
								if !parameter.auto && v.duration != _|_ {
									duration: v.duration
								}
							}
						},
					]
					if parameter.canary.trafficRoutings != _|_ {
						trafficRoutings: [
							for routing in parameter.canary.trafficRoutings {
								if routing.service != "" {
									service: routing.service
								}
								if routing.service == "" {
									service: context.name
								}
								gracePeriodSeconds: routing.gracePeriodSeconds
								type:               routing.type
								ingress: {
									if routing.ingress.name != "" {
										name: routing.ingress.name
									}
									if routing.ingress.name == "" {
										name: context.name
									}
								}
							},
						]
					}
				}
			}
		}
	}
}
```
Fix the kruise-rollout.cue definition so that it can not only support ref-objects typed component but also support webservice typed component.

2022-05-16 07:12 UTC, wangyikewxgm requested changes

2022-05-16 07:12 UTC, wangyikewxgm commented on experimental/addons/kruise-rollout/template.yaml
> +        type: apply-application
There is no need add these lines. Please remove

2022-05-16 07:20 UTC, wangyikewxgm submitted a review, later dismissed
LGTM

2022-05-16 10:00 UTC, barnettZQG commented on experimental/addons/kruise-rollout/definitions/kruise-rollout.cue
> +		appliesToWorkloads: ["*"]
Please set the appliesToWorkloads, does the rollout only support the Deployment and CloneSet?
```
appliesToWorkloads: ["deployments.apps", "clonesets.apps.kruise.io"]
```

2022-05-20 08:13 UTC, wangyikewxgm approved these changes
LGTM, good job, thanks

2022-05-20 09:26 UTC, merged